pipeline {
    agent any

    stages {
        stage('Docker_Build_Nginx') {
            steps {
                dir("Docker"){
                    sh """
                        pwd
			ls -l
                        echo "my-nginx:v1.0.${env.BUILD_TAG}"
                        docker build --tag "my-nginx:v1.0.${env.BUILD_TAG}" .
                    """
                }
            }
        }
    }
}
