pipeline {
    agent any

    stages {
        stage('Docker_Build_Nginx') {
            steps {
                dir("Docker"){
                    sh """
                        pwd
                        ls -l
                        echo "my-nginx:v1.0.${env.BUILD_ID}"
                        docker build --tag "my-nginx:v1.0.${env.BUILD_ID}" .
                    """
                }
            }
        }
        stage('Docker_Run_Nginx') {
            agent {
                docker { 
                    image "my-nginx:v1.0.${env.BUILD_ID}"
                    reuseNode true          // share workspace across agents
                    }
            }
            steps {
                sh """
                    pwd
                    ls -l
                    ps 
                    sleep 120
                """
            }
        }
    }
}
